#!/usr/bin/env bash

# Usage:
#   tmux-broadcast [-s] <command>
#   -s : run silently

SILENT=0

# Parse options
while getopts "s" opt; do
	case "$opt" in
	s) SILENT=1 ;;
	*)
		echo "Usage: tmux-broadcast [-s] <command>"
		echo " -s : run silently"
		exit 1
		;;
	esac
done
shift $((OPTIND - 1))

CMD="$*"

if [ -z "$CMD" ]; then
	echo "Usage: tmux-broadcast -s <command>"
	exit 1
fi

tmux list-panes -a -F "#{session_name}:#{window_index}.#{pane_index} #{pane_current_command}" |
	while read -r pane_process; do
		IFS=' ' read -ra pane_process <<<"$pane_process"
		pane="${pane_process[0]}"
		cmd="${pane_process[1]}"

		case "$cmd" in
		bash | zsh | fish | sh) # only send to shells
			tmux send-keys -t "$pane" "$CMD" C-b C-m
			;;
		esac
	done
