#!/usr/bin/env bash

# tmux-broadcast.sh
#
# Broadcast a command to all panes running a shell.
#
# Usage:
#   ./tmux-broadcast.sh [-s] "your command here"
#
# Options:
#   -s    Silent mode (just send command + Enter, no extra keys)
#   -h    Show this help message

SILENT=0
help_info() {

	echo "Usage: tmux-broadcast [-s, --slient] <command>"
	echo
	echo "Options:"
	echo "  -s    Silent mode"
	echo "  -h    Show this help message"
}
# Parse flags
while [[ "$1" == -* ]]; do
	case "$1" in
	-s | --slient) SILENT=1 ;;
	-h | --help)
		help_info
		exit 0
		;;
	*) echo "Unknown option: $1" && exit 1 ;;
	esac
	shift
done

CMD="$*"

if [ -z "$CMD" ]; then
	help_info
	exit 1
fi

tmux list-panes -a -F "#{session_name}:#{window_index}.#{pane_index} #{pane_current_command}" |
	while read -r pane_process; do
		IFS=' ' read -ra pane_process <<<"$pane_process"
		pane="${pane_process[0]}"
		cmd="${pane_process[1]}"

		case "$cmd" in
		bash | zsh | fish | sh) # only send to shells
			if [[ $SILENT -eq 1 ]]; then
				tmux send-keys -t "$pane" "$CMD" C-b C-m
			else
				tmux send-keys -t "$pane" "$CMD" C-m
			fi
			;;
		esac
	done
